name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2                                       
        with:                                                               
          python-version: 3.9
      
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - run: python -m venv ./.venv && . ./.venv/bin/activate && 
           pip install -r requirements.txt
      
#       - name: Install flake8
#         # if no cache hit in our pip cache
#         if: steps.cache-venv.outputs.cache-hit != 'true'
#         run: pip install flake8

      - name: Run flake8
        run: | # mutliline script. Place a pipe to preserve \n
          echo 'Running flake'        
          flake8 .
