name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2                                       
        with:                                                               
          python-version: 3.9

      - uses: actions/cache@v2                                                                     
        id: pip-cache
        with:
          path: |
            ~/.cache/pip

          key: pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install flake8

        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: pip install flake8

      - name: Run flake8
        run: flake8 .
          # echo 'Running flake'        
          # flake8 .
